import '../models/car_model.dart';

final List<Car> allCarsData = [
  // --- ACURA ---
  const Car(
    id: 'acura_integra',
    brand: 'Acura',
    model: 'Integra',
    price: 3200000,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/78/%E2%80%9823_Acura_Integra_A-Spec.jpg',
    description: 'A premium sport compact that delivers a unique driving experience.',
    rating: 4.5,
    reviews: 120,
    topSpeed: 235,
    acceleration: 7.0,
    seats: 5,
    horsepower: 200,
    transmission: 'CVT/Manual',
    category: 'SDN',
    bodyType: 'Liftback',
    officialUrl: 'https://www.acura.com/cars/integra',
    keyFeatures: ['Premium Audio', 'A-Spec Package', 'Variable Steering'],
    fuelType: 'Petrol',
  ),

  // --- ALFA ROMEO ---
  const Car(
    id: 'alfa_giulia',
    brand: 'Alfa Romeo',
    model: 'Giulia',
    price: 4500000,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/6f/Alfa_Romeo_Giulia_Veloce_IMG_5945.jpg',
    description: 'Italian style meets exhilarating performance in this luxury sedan.',
    rating: 4.7,
    reviews: 85,
    topSpeed: 240,
    acceleration: 5.1,
    seats: 5,
    horsepower: 280,
    transmission: 'Auto',
    category: 'Luxury',
    bodyType: 'Sedan',
    officialUrl: 'https://www.alfaromeousa.com/vehicles/giulia',
    keyFeatures: ['Italian Design', 'Q4 AWD', 'Carbon Fiber Driveshaft'],
    fuelType: 'Petrol',
  ),

  // --- ASTON MARTIN ---
  const Car(
    id: 'aston_db12',
    brand: 'Aston Martin',
    model: 'DB12',
    price: 35000000,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/a6/Aston_Martin_DB12_IMG_0286.jpg',
    description: 'The world\'s first Super Tourer. A new era of performance and luxury.',
    rating: 4.9,
    reviews: 42,
    topSpeed: 325,
    acceleration: 3.5,
    seats: 4,
    horsepower: 671,
    transmission: 'Auto',
    category: 'Sports',
    bodyType: 'Coupe',
    officialUrl: 'https://www.astonmartin.com/en/models/db12',
    keyFeatures: ['V8 Twin-Turbo', 'Bespoke Interior', 'Adaptive Suspension'],
    fuelType: 'Petrol',
  ),

  // --- AUDI ---
  const Car(
    id: 'audi_a6',
    brand: 'Audi',
    model: 'A6',
    price: 6400000,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/ed/Audi_A6_I_Genf_2018.jpg',
    description: 'Progressive design and advanced technologies define the Audi A6.',
    rating: 4.6,
    reviews: 150,
    topSpeed: 250,
    acceleration: 6.8,
    seats: 5,
    horsepower: 261,
    transmission: 'Auto',
    category: 'Luxury',
    bodyType: 'Sedan',
    officialUrl: 'https://www.audi.com/en/models.html',
    keyFeatures: ['Quattro AWD', 'Virtual Cockpit', 'Matrix LED'],
    fuelType: 'Petrol',
  ),

  // --- BENTLEY ---
  const Car(
    id: 'bentley_continental',
    brand: 'Bentley',
    model: 'Continental GT',
    price: 42000000,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/36/0_Bentley_Continental_GT_%283rd_gen.%29_1.jpg',
    description: 'The definitive grand tourer, capable of crossing continents in style.',
    rating: 4.9,
    reviews: 90,
    topSpeed: 335,
    acceleration: 3.6,
    seats: 4,
    horsepower: 650,
    transmission: 'Auto',
    category: 'Luxury',
    bodyType: 'Coupe',
    officialUrl: 'https://www.bentleymotors.com/en/models/continental-gt.html',
    keyFeatures: ['W12 Engine', 'Handcrafted Interior', 'Rotating Display'],
    fuelType: 'Petrol',
  ),

  // --- BMW ---
  const Car(
    id: 'bmw_x5',
    brand: 'BMW',
    model: 'X5',
    price: 9800000,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/43/2020_BMW_X5_xDrive30d_M_Sport_Automatic_3.0_Front.jpg',
    description: 'The boss is back. The BMW X5 offers presence, power and functionality.',
    rating: 4.8,
    reviews: 310,
    topSpeed: 243,
    acceleration: 5.3,
    seats: 5,
    horsepower: 335,
    transmission: 'Auto',
    category: 'SUV',
    bodyType: 'SUV',
    officialUrl: 'https://www.bmw.com/en/all-models.html',
    keyFeatures: ['xDrive', 'Laser Light', 'Gesture Control'],
    fuelType: 'Diesel',
  ),

  // --- BUGATTI ---
  const Car(
    id: 'bugatti_chiron',
    brand: 'Bugatti',
    model: 'Chiron',
    price: 250000000,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/32/2018_Bugatti_Chiron_3.jpg',
    description: 'The fastest, most powerful, and exclusive production super sports car.',
    rating: 5.0,
    reviews: 15,
    topSpeed: 420,
    acceleration: 2.4,
    seats: 2,
    horsepower: 1500,
    transmission: 'Auto',
    category: 'Sports',
    bodyType: 'Coupe',
    officialUrl: 'https://www.bugatti.com/models/chiron-models/chiron/',
    keyFeatures: ['W16 Engine', '420 km/h Top Speed', 'Carbon Monocoque'],
    fuelType: 'Petrol',
  ),

  // --- BUICK ---
  const Car(
    id: 'buick_enclave',
    brand: 'Buick',
    model: 'Enclave',
    price: 4500000,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/0e/Buick_Enclave.jpg',
    description: 'The Enclave is a mid-size luxury SUV with room for up to seven.',
    rating: 4.4,
    reviews: 78,
    topSpeed: 210,
    acceleration: 7.0,
    seats: 7,
    horsepower: 310,
    transmission: 'Auto',
    category: 'SUV',
    bodyType: 'SUV',
    officialUrl: 'https://www.buick.com/suvs/enclave',
    keyFeatures: ['QuietTuning', 'Smart Slide Seating', 'AWD'],
    fuelType: 'Petrol',
  ),

  // --- BYD ---
  const Car(
    id: 'byd_atto3',
    brand: 'BYD',
    model: 'Atto 3',
    price: 3400000,
    imageUrl: 'https://www.byd.com/eu/car/atto3/galery/atto3-exterior-07.jpg',
    description: 'A stylish and efficient electric SUV for the modern family.',
    rating: 4.6,
    reviews: 200,
    topSpeed: 160,
    acceleration: 7.3,
    seats: 5,
    horsepower: 201,
    transmission: 'Auto',
    category: 'ELC',
    bodyType: 'SUV',
    officialUrl: 'https://www.byd.com/en/car/atto3',
    keyFeatures: ['Blade Battery', 'Rotating Screen', 'V2L'],
    fuelType: 'Electric',
  ),

  // --- CADILLAC ---
  const Car(
    id: 'cadillac_escalade',
    brand: 'Cadillac',
    model: 'Escalade',
    price: 12000000,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/23/Cadillac_Escalade_III_front.JPG',
    description: 'The Escalade is the crown jewel of Cadillac, setting the standard for luxury SUVs.',
    rating: 4.8,
    reviews: 145,
    topSpeed: 180,
    acceleration: 6.0,
    seats: 7,
    horsepower: 420,
    transmission: 'Auto',
    category: 'Luxury',
    bodyType: 'SUV',
    officialUrl: 'https://www.cadillac.com/suvs/escalade',
    keyFeatures: ['Curved OLED', 'Super Cruise', 'AKG Audio'],
    fuelType: 'Petrol',
  ),

  // --- CHEVROLET ---
  const Car(
    id: 'chevy_corvette',
    brand: 'Chevrolet',
    model: 'Corvette Stingray',
    price: 9500000,
    imageUrl: 'https://www.apchevy.com/inventory/new-East%2BDundee-2025-Chevrolet-Corvette%2BStingray-3LT-1G1YC2D48S5112708/1.jpg',
    description: 'A precision sports car that stands alone. The mid-engine masterpiece.',
    rating: 4.8,
    reviews: 350,
    topSpeed: 312,
    acceleration: 2.9,
    seats: 2,
    horsepower: 495,
    transmission: 'Auto',
    category: 'Sports',
    bodyType: 'Coupe',
    officialUrl: 'https://www.chevrolet.com/performance/corvette',
    keyFeatures: ['Mid-Engine', 'Performance Data Recorder', 'Magnetic Ride'],
    fuelType: 'Petrol',
  ),

  // --- CHERY ---
  const Car(
    id: 'chery_tiggo8',
    brand: 'Chery',
    model: 'Tiggo 8 Pro',
    price: 3500000,
    imageUrl: 'https://static.autox.com/uploads/2022/05/Chery-Tiggo-8-Pro-front-three-quarter.jpg',
    description: 'A luxurious 7-seater SUV with advanced technology and comfort.',
    rating: 4.4,
    reviews: 60,
    topSpeed: 200,
    acceleration: 8.9,
    seats: 7,
    horsepower: 197,
    transmission: 'DCT',
    category: 'SUV',
    bodyType: 'SUV',
    officialUrl: 'https://www.cheryinternational.com/',
    keyFeatures: ['Sony Sound System', 'ADAS', 'Panoramic Sunroof'],
    fuelType: 'Petrol',
  ),

  // --- CHRYSLER ---
  const Car(
    id: 'chrysler_pacifica',
    brand: 'Chrysler',
    model: 'Pacifica',
    price: 5200000,
    imageUrl: 'https://cdn.motor1.com/images/mgl/0ANk5/s1/2023-chrysler-pacifica.jpg',
    description: 'The most advanced minivan in its class, perfect for families.',
    rating: 4.7,
    reviews: 120,
    topSpeed: 180,
    acceleration: 7.5,
    seats: 7,
    horsepower: 287,
    transmission: 'Auto',
    category: 'MPV',
    bodyType: 'Minivan',
    officialUrl: 'https://www.chrysler.com/pacifica.html',
    keyFeatures: ['Stow \'n Go', 'Uconnect 5', 'AWD'],
    fuelType: 'Hybrid',
  ),

  // --- CITROEN ---
  const Car(
    id: 'citroen_c5',
    brand: 'Citroën',
    model: 'C5 Aircross',
    price: 3700000,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/62/2022_Citroen_C5_Aircross_Facelift.jpg',
    description: 'Comfort is the new cool. Designed for ultimate ride quality.',
    rating: 4.3,
    reviews: 80,
    topSpeed: 195,
    acceleration: 9.0,
    seats: 5,
    horsepower: 177,
    transmission: 'Auto',
    category: 'SUV',
    bodyType: 'SUV',
    officialUrl: 'https://www.citroen.com/en/models/c5-aircross.html',
    keyFeatures: ['Progressive Hydraulic Cushions', 'Advanced Comfort Seats', 'Modular Rear Seats'],
    fuelType: 'Diesel',
  ),

  // --- CUPRA ---
  const Car(
    id: 'cupra_formentor',
    brand: 'Cupra',
    model: 'Formentor',
    price: 4800000,
    imageUrl: 'https://images.unsplash.com/photo-1662497645161-551ee6718873?auto=format&fit=crop&w=600',
    description: 'The first vehicle uniquely designed and developed for the CUPRA brand.',
    rating: 4.6,
    reviews: 65,
    topSpeed: 250,
    acceleration: 4.9,
    seats: 5,
    horsepower: 310,
    transmission: 'DSG',
    category: 'SUV',
    bodyType: 'Crossover',
    officialUrl: 'https://www.cupraofficial.com/cars/cupra-range/formentor',
    keyFeatures: ['Matrix LED', '12" Infotainment', 'DCC'],
    fuelType: 'Petrol',
  ),

  // --- DODGE ---
  const Car(
    id: 'dodge_challenger',
    brand: 'Dodge',
    model: 'Challenger Hellcat',
    price: 8500000,
    imageUrl: 'https://images.unsplash.com/photo-1626668893632-6f3a4466d22f?auto=format&fit=crop&w=600',
    description: 'The world\'s most powerful muscle car. Pure American horsepower.',
    rating: 4.8,
    reviews: 400,
    topSpeed: 320,
    acceleration: 3.4,
    seats: 5,
    horsepower: 717,
    transmission: 'Auto',
    category: 'Sports',
    bodyType: 'Coupe',
    officialUrl: 'https://www.dodge.com/challenger.html',
    keyFeatures: ['Supercharged HEMI', 'Widebody', 'Launch Control'],
    fuelType: 'Petrol',
  ),

  // --- FERRARI ---
  const Car(
    id: 'ferrari_sf90',
    brand: 'Ferrari',
    model: 'SF90 Stradale',
    price: 75000000,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/8e/2020_Ferrari_SF90_Stradale_%28Front%29.jpg',
    description: 'The first Series Production PHEV Spider from the Prancing Horse.',
    rating: 5.0,
    reviews: 40,
    topSpeed: 340,
    acceleration: 2.5,
    seats: 2,
    horsepower: 986,
    transmission: 'Auto',
    category: 'Sports',
    bodyType: 'Coupe',
    officialUrl: 'https://www.ferrari.com/en-EN/auto/sf90-stradale',
    keyFeatures: ['PHEV', 'eManettino', 'AWD'],
    fuelType: 'Hybrid',
  ),

  // --- FIAT ---
  const Car(
    id: 'fiat_500e',
    brand: 'Fiat',
    model: '500e',
    price: 2800000,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/5/54/2021_Fiat_500e_La_Prima_front.jpg',
    description: 'The icon, reinvented. 100% electric, 100% Italian.',
    rating: 4.5,
    reviews: 150,
    topSpeed: 150,
    acceleration: 9.0,
    seats: 4,
    horsepower: 118,
    transmission: 'Auto',
    category: 'ELC',
    bodyType: 'Hatchback',
    officialUrl: 'https://www.fiat.com/500-electric',
    keyFeatures: ['Level 2 Autonomous Driving', 'Fast Charging', 'Iconic Design'],
    fuelType: 'Electric',
  ),

  // --- FORD ---
  const Car(
    id: 'ford_mustang',
    brand: 'Ford',
    model: 'Mustang GT',
    price: 7490000,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/b4/2024_Ford_Mustang_GT_in_Yellow_Splash.jpg',
    description: 'The world\'s best-selling sports car, offering iconic style and performance.',
    rating: 4.7,
    reviews: 560,
    topSpeed: 250,
    acceleration: 4.3,
    seats: 4,
    horsepower: 450,
    transmission: 'Manual/Auto',
    category: 'Sports',
    bodyType: 'Coupe',
    officialUrl: 'https://www.ford.com/cars/mustang/',
    keyFeatures: ['5.0L V8', 'Track Apps', 'Active Exhaust'],
    fuelType: 'Petrol',
  ),

  // --- FORCE MOTORS ---
  const Car(
    id: 'force_gurkha',
    brand: 'Force Motors',
    model: 'Gurkha',
    price: 1500000,
    imageUrl: 'https://www.autocarindia.com/datastore/images/cms-originals/480x360/2024-Force-Gurkha-5-door-front-three-quarters.jpg',
    description: 'The extreme off-road vehicle for the true adventurer.',
    rating: 4.2,
    reviews: 90,
    topSpeed: 140,
    acceleration: 14.0,
    seats: 4,
    horsepower: 90,
    transmission: 'Manual',
    category: 'SUV',
    bodyType: 'SUV',
    officialUrl: 'https://www.forcemotors.com/vehicle/gurkha',
    keyFeatures: ['Snorkel', 'Diff Locks', '4x4'],
    fuelType: 'Diesel',
  ),

  // --- GENESIS ---
  const Car(
    id: 'genesis_g80',
    brand: 'Genesis',
    model: 'G80',
    price: 6500000,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/24/Genesis_G80_3.5T_AWD.jpg',
    description: 'Athletic elegance in a luxury sedan.',
    rating: 4.8,
    reviews: 70,
    topSpeed: 250,
    acceleration: 4.9,
    seats: 5,
    horsepower: 375,
    transmission: 'Auto',
    category: 'Luxury',
    bodyType: 'Sedan',
    officialUrl: 'https://www.genesis.com/worldwide/en/models/g80.html',
    keyFeatures: ['3.5T V6', 'Remote Smart Parking', 'Ergo Motion Seat'],
    fuelType: 'Petrol',
  ),

  // --- GEELY ---
  const Car(
    id: 'geely_coolray',
    brand: 'Geely',
    model: 'Coolray',
    price: 2200000,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/c/c5/Geely_Binyue_002.jpg',
    description: 'A smart SUV with sporty design and intelligent technology.',
    rating: 4.3,
    reviews: 50,
    topSpeed: 195,
    acceleration: 7.9,
    seats: 5,
    horsepower: 177,
    transmission: 'DCT',
    category: 'SUV',
    bodyType: 'SUV',
    officialUrl: 'https://global.geely.com/car/coolray',
    keyFeatures: ['Auto Park', '360 Camera', 'Turbo Engine'],
    fuelType: 'Petrol',
  ),

  // --- GMC ---
  const Car(
    id: 'gmc_hummer_ev',
    brand: 'GMC',
    model: 'Hummer EV',
    price: 9000000,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/04/GMC_Hummer_EV_2022.jpg',
    description: 'The world\'s first all-electric supertruck.',
    rating: 4.7,
    reviews: 80,
    topSpeed: 170,
    acceleration: 3.0,
    seats: 5,
    horsepower: 1000,
    transmission: 'Auto',
    category: 'ELC',
    bodyType: 'Pickup/SUV',
    officialUrl: 'https://www.gmc.com/electric/hummer-ev',
    keyFeatures: ['CrabWalk', 'Extract Mode', 'Infinity Roof'],
    fuelType: 'Electric',
  ),

  // --- GREAT WALL MOTORS ---
  const Car(
    id: 'gwm_tank300',
    brand: 'Great Wall Motors',
    model: 'Tank 300',
    price: 3200000,
    imageUrl: 'https://www.thecarconnection.com/images/sized/960/24294/2023_gwm_tank_300_angularfront.jpg',
    description: 'A smart luxury off-road SUV that combines retro chic with modern tech.',
    rating: 4.4,
    reviews: 45,
    topSpeed: 170,
    acceleration: 9.5,
    seats: 5,
    horsepower: 227,
    transmission: 'Auto',
    category: 'SUV',
    bodyType: 'SUV',
    officialUrl: 'https://www.gwm-global.com/brands/tank/',
    keyFeatures: ['Tank Turn', 'Diff Locks', 'Massage Seats'],
    fuelType: 'Petrol',
  ),

  // --- HONDA ---
  const Car(
    id: 'honda_civic_type_r',
    brand: 'Honda',
    model: 'Civic Type R',
    price: 5500000,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/f/f9/2023_Honda_Civic_Type_R_front_4.30.23.jpg',
    description: 'The most powerful Civic ever. Born on the track, ready for the street.',
    rating: 4.8,
    reviews: 210,
    topSpeed: 272,
    acceleration: 5.4,
    seats: 4,
    horsepower: 315,
    transmission: 'Manual',
    category: 'Hatch',
    bodyType: 'Hatchback',
    officialUrl: 'https://automobiles.honda.com/civic-type-r',
    keyFeatures: ['VTEC Turbo', 'Brembo Brakes', 'Rear Wing'],
    fuelType: 'Petrol',
  ),

  // --- HYUNDAI ---
  const Car(
    id: 'hyundai_ioniq5',
    brand: 'Hyundai',
    model: 'IONIQ 5',
    price: 4500000,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/09/2022_Hyundai_Ioniq_5_Ultimate_AWD.jpg',
    description: 'Retro-futuristic design meets cutting-edge electric performance.',
    rating: 4.7,
    reviews: 320,
    topSpeed: 185,
    acceleration: 5.2,
    seats: 5,
    horsepower: 320,
    transmission: 'Auto',
    category: 'ELC',
    bodyType: 'SUV',
    officialUrl: 'https://www.hyundai.com/worldwide/en/ionic/ioniq5',
    keyFeatures: ['E-GMP Platform', 'V2L', 'Relaxation Seats'],
    fuelType: 'Electric',
  ),

  // --- INFINITI ---
  const Car(
    id: 'infiniti_qx60',
    brand: 'Infiniti',
    model: 'QX60',
    price: 5500000,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/a4/2022_Infiniti_QX60_SENSORY_3.5L_front_left.jpg',
    description: 'Conquer life in style with this luxurious 7-seater SUV.',
    rating: 4.5,
    reviews: 60,
    topSpeed: 210,
    acceleration: 7.3,
    seats: 7,
    horsepower: 295,
    transmission: 'Auto',
    category: 'SUV',
    bodyType: 'SUV',
    officialUrl: 'https://www.infinitiusa.com/vehicles/crossovers-suvs/qx60',
    keyFeatures: ['ProPILOT Assist', 'Zero Gravity Seats', 'Bose Performance'],
    fuelType: 'Petrol',
  ),

  // --- ISUZU ---
  const Car(
    id: 'isuzu_dmax',
    brand: 'Isuzu',
    model: 'D-Max V-Cross',
    price: 2300000,
    imageUrl: 'https://cdni.autocarindia.com/ExtraImages/20210629022200_Isuzu-D-Max-V-Cross-front-three-quarter.jpg',
    description: 'India\'s lifestyle pickup that is tough, powerful, and stylish.',
    rating: 4.3,
    reviews: 110,
    topSpeed: 175,
    acceleration: 12.0,
    seats: 5,
    horsepower: 163,
    transmission: 'Auto',
    category: 'Utility',
    bodyType: 'Pickup',
    officialUrl: 'https://www.isuzu.in/d-max-v-cross/',
    keyFeatures: ['Shift-on-the-fly 4WD', 'Bi-LED Lights', '7-inch Touchscreen'],
    fuelType: 'Diesel',
  ),

  // --- JAGUAR ---
  const Car(
    id: 'jaguar_f_type',
    brand: 'Jaguar',
    model: 'F-TYPE',
    price: 9800000,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/d4/2019_Jaguar_F-Type_R-Dynamic_front.jpg',
    description: 'Jaguar performance art. A pure sports car with a stunning design.',
    rating: 4.6,
    reviews: 110,
    topSpeed: 300,
    acceleration: 3.7,
    seats: 2,
    horsepower: 575,
    transmission: 'Auto',
    category: 'Sports',
    bodyType: 'Coupe',
    officialUrl: 'https://www.jaguar.com/vehicles/f-type/index.html',
    keyFeatures: ['Supercharged V8', 'Active Exhaust', 'Touch Pro'],
    fuelType: 'Petrol',
  ),

  // --- JEEP ---
  const Car(
    id: 'jeep_wrangler',
    brand: 'Jeep',
    model: 'Wrangler',
    price: 6500000,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/0f/Jeep_Wrangler_%28JL%29_in_Silver.jpg',
    description: 'The original 4x4. Unmatched off-road capability and open-air freedom.',
    rating: 4.6,
    reviews: 450,
    topSpeed: 160,
    acceleration: 7.5,
    seats: 5,
    horsepower: 285,
    transmission: 'Auto/Manual',
    category: 'SUV',
    bodyType: 'SUV',
    officialUrl: 'https://www.jeep.com/wrangler.html',
    keyFeatures: ['Trail Rated', 'Removable Doors', '4x4 Systems'],
    fuelType: 'Petrol',
  ),

  // --- KIA ---
  const Car(
    id: 'kia_ev6',
    brand: 'Kia',
    model: 'EV6',
    price: 6000000,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/70/2022_Kia_EV6_GT-Line.jpg',
    description: 'Inspiring every journey. A dedicated EV with impressive range and power.',
    rating: 4.7,
    reviews: 180,
    topSpeed: 260,
    acceleration: 3.5,
    seats: 5,
    horsepower: 576,
    transmission: 'Auto',
    category: 'ELC',
    bodyType: 'SUV',
    officialUrl: 'https://www.kia.com/worldwide/vehicles/ev6.html',
    keyFeatures: ['800V Charging', 'V2L', 'Augmented Reality HUD'],
    fuelType: 'Electric',
  ),

  // --- LAMBORGHINI ---
  const Car(
    id: 'lambo_revuelto',
    brand: 'Lamborghini',
    model: 'Revuelto',
    price: 89000000,
    imageUrl: 'https://cdn.motor1.com/images/mgl/0x0jPo/s1/lamborghini-revuelto-front-three-quarters.jpg',
    description: 'From now on. The first High Performance Electrified Vehicle (HPEV).',
    rating: 5.0,
    reviews: 10,
    topSpeed: 350,
    acceleration: 2.5,
    seats: 2,
    horsepower: 1001,
    transmission: 'Auto',
    category: 'Sports',
    bodyType: 'Coupe',
    officialUrl: 'https://www.lamborghini.com/en-en/models/revuelto',
    keyFeatures: ['V12 Hybrid', 'Carbon Fuselage', 'Active Aerodynamics'],
    fuelType: 'Hybrid',
  ),

  // --- LAND ROVER ---
  const Car(
    id: 'land_rover_defender',
    brand: 'Land Rover',
    model: 'Defender',
    price: 11000000,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/04/2020_Land_Rover_Defender_110_SE_D180.jpg',
    description: 'Capable of great things. An icon reimagined for the 21st century.',
    rating: 4.8,
    reviews: 230,
    topSpeed: 191,
    acceleration: 6.0,
    seats: 7,
    horsepower: 395,
    transmission: 'Auto',
    category: 'SUV',
    bodyType: 'SUV',
    officialUrl: 'https://www.landrover.com/vehicles/defender/index.html',
    keyFeatures: ['Terrain Response', 'ClearSight Ground View', 'Robust Interior'],
    fuelType: 'Petrol/Diesel',
  ),

  // --- LEXUS ---
  const Car(
    id: 'lexus_rx',
    brand: 'Lexus',
    model: 'RX',
    price: 9500000,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/c/cf/2023_Lexus_RX_350h_Premium%2B_front.jpg',
    description: 'The pioneer of the luxury crossover segment, now more refined than ever.',
    rating: 4.7,
    reviews: 190,
    topSpeed: 200,
    acceleration: 7.9,
    seats: 5,
    horsepower: 275,
    transmission: 'Auto',
    category: 'Luxury',
    bodyType: 'SUV',
    officialUrl: 'https://www.lexus.com/models/RX',
    keyFeatures: ['Lexus Safety System+', 'Mark Levinson Audio', 'AWD'],
    fuelType: 'Hybrid',
  ),

  // --- MAHINDRA ---
  const Car(
    id: 'mahindra_xuv700',
    brand: 'Mahindra',
    model: 'XUV700',
    price: 2600000,
    imageUrl: 'https://cdni.autocarindia.com/ExtraImages/20211102101919_XUV700.jpg',
    description: 'A tech-laden SUV that represents a new era for Mahindra.',
    rating: 4.6,
    reviews: 550,
    topSpeed: 200,
    acceleration: 9.5,
    seats: 7,
    horsepower: 197,
    transmission: 'Auto',
    category: 'SUV',
    bodyType: 'SUV',
    officialUrl: 'https://auto.mahindra.com/suv/xuv700',
    keyFeatures: ['ADAS L2', 'Skyroof', 'Dual 10.25" Screens'],
    fuelType: 'Diesel',
  ),
  
    // --- MARUTI SUZUKI ---
  const Car(
    id: 'maruti_grand_vitara',
    brand: 'Maruti Suzuki',
    model: 'Grand Vitara',
    price: 1900000,
    imageUrl: 'https://cdni.autocarindia.com/ExtraImages/20220720040954_Maruti-Grand-Vitara-front-3-quarters.jpg',
    description: 'A game-changing hybrid SUV with class-leading fuel efficiency.',
    rating: 4.5,
    reviews: 650,
    topSpeed: 170,
    acceleration: 12.0,
    seats: 5,
    horsepower: 114,
    transmission: 'e-CVT',
    category: 'SUV',
    bodyType: 'SUV',
    officialUrl: 'https://www.marutisuzuki.com/grand-vitara',
    keyFeatures: ['Intelligent Electric Hybrid', 'AllGrip (AWD)', 'Panoramic Sunroof'],
    fuelType: 'Hybrid',
  ),

  // --- MASERATI (Bonus for premium feel) ---
  const Car(
    id: 'maserati_mc20',
    brand: 'Maserati',
    model: 'MC20',
    price: 36000000,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e1/Maserati_MC20_2022.jpg',
    description: 'The super sports car that pushes the boundaries of time.',
    rating: 4.8,
    reviews: 35,
    topSpeed: 325,
    acceleration: 2.9,
    seats: 2,
    horsepower: 621,
    transmission: 'Auto',
    category: 'Sports',
    bodyType: 'Coupe',
    officialUrl: 'https://www.maserati.com/global/en/models/mc20',
    keyFeatures: ['Nettuno V6', 'Carbon Fibre Monocoque', 'Butterfly Doors'],
    fuelType: 'Petrol',
  ),

  // --- MERCEDES-BENZ ---
  const Car(
    id: 'mercedes_s_class',
    brand: 'Mercedes-Benz',
    model: 'S-Class',
    price: 18000000,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/b3/2021_Mercedes-Benz_S_500_AMG_Line_Plus.jpg',
    description: 'The world\'s best car? The S-Class sets the standard for luxury sedans.',
    rating: 4.9,
    reviews: 160,
    topSpeed: 250,
    acceleration: 5.1,
    seats: 5,
    horsepower: 429,
    transmission: 'Auto',
    category: 'Luxury',
    bodyType: 'Sedan',
    officialUrl: 'https://www.mercedes-benz.com/en/vehicles/s-class/',
    keyFeatures: ['MBUX', 'Rear Axle Steering', 'Burmester 4D Sound'],
    fuelType: 'Hybrid',
  ),
  
    // --- MINI ---
  const Car(
    id: 'mini_cooper',
    brand: 'Mini',
    model: 'Cooper S',
    price: 4500000,
    imageUrl: 'https://cdn.motor1.com/images/mgl/YxVZrA/s1/2024-mini-cooper-s-front-quarter.jpg',
    description: 'Go-kart handling and iconic British design.',
    rating: 4.6,
    reviews: 180,
    topSpeed: 235,
    acceleration: 6.7,
    seats: 4,
    horsepower: 189,
    transmission: 'Auto',
    category: 'Hatch',
    bodyType: 'Hatchback',
    officialUrl: 'https://www.mini.com/en_MS/home/range/mini-3-door-hatch.html',
    keyFeatures: ['TwinPower Turbo', 'Union Jack Lights', '8.8" Touchscreen'],
    fuelType: 'Petrol',
  ),

  // --- MITSUBISHI ---
  const Car(
    id: 'mitsubishi_outlander',
    brand: 'Mitsubishi',
    model: 'Outlander',
    price: 3200000,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/2e/2022_Mitsubishi_Outlander_SE_AWD.jpg',
    description: 'A bold new direction for the brand. Rugged yet refined.',
    rating: 4.4,
    reviews: 95,
    topSpeed: 190,
    acceleration: 9.8,
    seats: 7,
    horsepower: 181,
    transmission: 'CVT',
    category: 'SUV',
    bodyType: 'SUV',
    officialUrl: 'https://www.mitsubishi-motors.com/en/products/outlander/',
    keyFeatures: ['S-AWC', 'MI-PILOT', 'Digital Cockpit'],
    fuelType: 'Petrol',
  ),

  // --- NISSAN ---
  const Car(
    id: 'nissan_gtr',
    brand: 'Nissan',
    model: 'GT-R',
    price: 21200000,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/3f/2017_Nissan_GT-R_Premium_in_Pearl_White.jpg',
    description: 'Godzilla. A supercar that can be driven every day.',
    rating: 4.7,
    reviews: 200,
    topSpeed: 315,
    acceleration: 2.9,
    seats: 4,
    horsepower: 565,
    transmission: 'Auto',
    category: 'Sports',
    bodyType: 'Coupe',
    officialUrl: 'https://www.nissan.usa.com/vehicles/sports-cars/gt-r.html',
    keyFeatures: ['AWD', 'Twin-Turbo V6', 'Hand-built Engine'],
    fuelType: 'Petrol',
  ),

  // --- OPEL ---
  const Car(
    id: 'opel_astra',
    brand: 'Opel',
    model: 'Astra',
    price: 2800000,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/0c/Opel_Astra_L_1.2_Turbo_130_Elegance_%28cropped%29.jpg',
    description: 'German engineering with a bold new design language.',
    rating: 4.2,
    reviews: 75,
    topSpeed: 210,
    acceleration: 8.5,
    seats: 5,
    horsepower: 130,
    transmission: 'Auto',
    category: 'Hatch',
    bodyType: 'Hatchback',
    officialUrl: 'https://www.opel.com/cars/astra-hatchback/index.html',
    keyFeatures: ['IntelliLux LED', 'Pure Panel', 'AGR Seats'],
    fuelType: 'Petrol/Hybrid',
  ),

  // --- PEUGEOT ---
  const Car(
    id: 'peugeot_408',
    brand: 'Peugeot',
    model: '408',
    price: 3400000,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/c/cf/Peugeot_408_2022_IMG_7125.jpg',
    description: 'A new breed of car with a dynamic fastback silhouette.',
    rating: 4.5,
    reviews: 55,
    topSpeed: 230,
    acceleration: 7.8,
    seats: 5,
    horsepower: 225,
    transmission: 'Auto',
    category: 'SDN',
    bodyType: 'Fastback',
    officialUrl: 'https://www.peugeot.com/en/models/new-408.html',
    keyFeatures: ['i-Cockpit', 'Focal Hi-Fi', 'Night Vision'],
    fuelType: 'Hybrid',
  ),

  // --- PORSCHE ---
  const Car(
    id: 'porsche_911',
    brand: 'Porsche',
    model: '911 GT3',
    price: 27500000,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/19/2022_Porsche_911_GT3_%28992%29_in_Sapphire_Blue_Metallic.jpg',
    description: 'A race car for the road. The purest expression of the 911.',
    rating: 5.0,
    reviews: 120,
    topSpeed: 318,
    acceleration: 3.4,
    seats: 2,
    horsepower: 502,
    transmission: 'Manual/PDK',
    category: 'Sports',
    bodyType: 'Coupe',
    officialUrl: 'https://www.porsche.com/usa/models/911/911-gt3-models/',
    keyFeatures: ['4.0L Flat-6', 'Swan Neck Wing', 'Double Wishbone Suspension'],
    fuelType: 'Petrol',
  ),

  // --- RENAULT ---
  const Car(
    id: 'renault_kiger',
    brand: 'Renault',
    model: 'Kiger',
    price: 850000,
    imageUrl: 'https://cdni.autocarindia.com/ExtraImages/20210203045046_Renault-Kiger.jpg',
    description: 'A sporty sub-4m SUV designed to stand out.',
    rating: 4.3,
    reviews: 350,
    topSpeed: 165,
    acceleration: 12.5,
    seats: 5,
    horsepower: 100,
    transmission: 'CVT',
    category: 'SUV',
    bodyType: 'Compact SUV',
    officialUrl: 'https://www.renault.co.in/cars/renault-kiger.html',
    keyFeatures: ['Wireless CarPlay', 'Turbo Engine', 'Multi-Sense Modes'],
    fuelType: 'Petrol',
  ),

  // --- ROLLS-ROYCE ---
  const Car(
    id: 'rr_phantom',
    brand: 'Rolls-Royce',
    model: 'Phantom',
    price: 100000000,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e0/2023_Rolls-Royce_Phantom_Series_II.jpg',
    description: 'The best car in the world. Unmatched luxury and presence.',
    rating: 5.0,
    reviews: 50,
    topSpeed: 250,
    acceleration: 5.3,
    seats: 4,
    horsepower: 563,
    transmission: 'Auto',
    category: 'Luxury',
    bodyType: 'Sedan',
    officialUrl: 'https://www.rolls-roycemotorcars.com/en_US/showroom/phantom.html',
    keyFeatures: ['Starlight Headliner', 'Gallery Dashboard', 'Magic Carpet Ride'],
    fuelType: 'Petrol',
  ),

  // --- SKODA ---
  const Car(
    id: 'skoda_kodiaq',
    brand: 'Škoda',
    model: 'Kodiaq',
    price: 3900000,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/75/2021_Skoda_Kodiaq_Style_facelift_front.jpg',
    description: 'A refined 7-seater SUV that offers maximum comfort and safety.',
    rating: 4.6,
    reviews: 210,
    topSpeed: 210,
    acceleration: 7.8,
    seats: 7,
    horsepower: 190,
    transmission: 'DSG',
    category: 'SUV',
    bodyType: 'SUV',
    officialUrl: 'https://www.skoda-auto.co.in/models/kodiaq/kodiaq-4x4',
    keyFeatures: ['Canton Sound', 'Virtual Cockpit', 'Dynamic Chassis Control'],
    fuelType: 'Petrol',
  ),

  // --- SUBARU ---
  const Car(
    id: 'subaru_wrx',
    brand: 'Subaru',
    model: 'WRX',
    price: 4000000,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/f/fd/2022_Subaru_WRX_Limited_in_Solar_Orange_Pearl.jpg',
    description: 'A rally-bred legend for the street.',
    rating: 4.5,
    reviews: 210,
    topSpeed: 240,
    acceleration: 5.5,
    seats: 5,
    horsepower: 271,
    transmission: 'Manual',
    category: 'SDN',
    bodyType: 'Sedan',
    officialUrl: 'https://www.subaru.com/vehicles/wrx/index.html',
    keyFeatures: ['Symmetrical AWD', 'Boxer Engine', 'Track-Tuned Suspension'],
    fuelType: 'Petrol',
  ),

  // --- SUZUKI (Global) ---
  const Car(
    id: 'suzuki_jimny',
    brand: 'Suzuki',
    model: 'Jimny',
    price: 1274000,
    imageUrl: 'https://cdni.autocarindia.com/ExtraImages/20230113053838_Maruti-Suzuki-Jimny-5-door.jpg',
    description: 'The lightweight off-roader loved around the world.',
    rating: 4.5,
    reviews: 500,
    topSpeed: 145,
    acceleration: 14.0,
    seats: 4,
    horsepower: 103,
    transmission: 'Auto/Manual',
    category: 'SUV',
    bodyType: 'SUV',
    officialUrl: 'https://www.globalsuzuki.com/automobile/lineup/jimny/',
    keyFeatures: ['ALLGRIP', 'Ladder Frame', 'Short Overhangs'],
    fuelType: 'Petrol',
  ),
  
    // --- TAT MOTORS ---
  const Car(
    id: 'tata_nexon',
    brand: 'Tata Motors',
    model: 'Nexon',
    price: 1400000,
    imageUrl: 'https://cdni.autocarindia.com/ExtraImages/20230914120256_Tata-Nexon.jpg',
    description: 'India\'s safest compact SUV with 5-star GNCAP rating.',
    rating: 4.5,
    reviews: 1500,
    topSpeed: 160,
    acceleration: 11.5,
    seats: 5,
    horsepower: 118,
    transmission: 'AMT/DCA',
    category: 'SUV',
    bodyType: 'Compact SUV',
    officialUrl: 'https://cars.tatamotors.com/cars/nexon',
    keyFeatures: ['5-Star Safety', 'JBL Audio', 'Ventilated Seats'],
    fuelType: 'Petrol/Diesel',
  ),

  // --- TESLA ---
  const Car(
    id: 'tesla_model_s',
    brand: 'Tesla',
    model: 'Model S Plaid',
    price: 12500000,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/44/Tesla_Model_S_Plaid.jpg',
    description: 'The quickest accelerating car in production today.',
    rating: 4.8,
    reviews: 300,
    topSpeed: 322,
    acceleration: 1.99,
    seats: 5,
    horsepower: 1020,
    transmission: 'Auto',
    category: 'ELC',
    bodyType: 'Sedan',
    officialUrl: 'https://www.tesla.com/models',
    keyFeatures: ['Tri-Motor', 'Yoke Steering', 'Gaming Computer'],
    fuelType: 'Electric',
  ),

  // --- TOYOTA ---
  const Car(
    id: 'toyota_land_cruiser',
    brand: 'Toyota',
    model: 'Land Cruiser',
    price: 21000000,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/3f/2022_Toyota_Land_Cruiser_300_Sahara_ZX.jpg',
    description: 'The King of 4WD. Unstoppable capability with premium luxury.',
    rating: 4.8,
    reviews: 400,
    topSpeed: 210,
    acceleration: 6.7,
    seats: 7,
    horsepower: 304,
    transmission: 'Auto',
    category: 'SUV',
    bodyType: 'SUV',
    officialUrl: 'https://www.toyota.com/landcruiser/',
    keyFeatures: ['TNGA-F Platform', 'Multi-Terrain Select', 'E-KDSS'],
    fuelType: 'Diesel',
  ),

  // --- VOLKSWAGEN (Common missing brand) ---
  const Car(
    id: 'vw_golf_r',
    brand: 'Volkswagen',
    model: 'Golf R',
    price: 4800000,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/c/c3/Volkswagen_Golf_VIII_R_IMG_4303.jpg',
    description: 'The ultimate hot hatch. Practicality meets performance.',
    rating: 4.7,
    reviews: 280,
    topSpeed: 250,
    acceleration: 4.7,
    seats: 5,
    horsepower: 315,
    transmission: 'DSG',
    category: 'Hatch',
    bodyType: 'Hatchback',
    officialUrl: 'https://www.vw.com/en/models/golf-r.html',
    keyFeatures: ['4MOTION AWD', 'Drift Mode', 'IQ.LIGHT'],
    fuelType: 'Petrol',
  ),
];
