// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmDp1rfvfL0cYjVUhHQ1MFbu71gQHHN4s',
    appId: '1:357951390056:web:e8405e8fe0a0881bf296dd',
    messagingSenderId: '357951390056',
    projectId: 'automobile-app-8f4a3',
    authDomain: 'automobile-app-8f4a3.firebaseapp.com',
    storageBucket: 'automobile-app-8f4a3.firebasestorage.app',
    measurementId: 'G-W3VRJV5Q13',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGdGuuGB9pTO-1cdlXos3P-HXj7xh2ouQ',
    appId: '1:357951390056:ios:013ac0fada17a75cf296dd',
    messagingSenderId: '357951390056',
    projectId: 'automobile-app-8f4a3',
    storageBucket: 'automobile-app-8f4a3.firebasestorage.app',
    iosBundleId: 'com.example.automobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGdGuuGB9pTO-1cdlXos3P-HXj7xh2ouQ',
    appId: '1:357951390056:ios:013ac0fada17a75cf296dd',
    messagingSenderId: '357951390056',
    projectId: 'automobile-app-8f4a3',
    storageBucket: 'automobile-app-8f4a3.firebasestorage.app',
    iosBundleId: 'com.example.automobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmDp1rfvfL0cYjVUhHQ1MFbu71gQHHN4s',
    appId: '1:357951390056:web:82685acc6e16fa56f296dd',
    messagingSenderId: '357951390056',
    projectId: 'automobile-app-8f4a3',
    authDomain: 'automobile-app-8f4a3.firebaseapp.com',
    storageBucket: 'automobile-app-8f4a3.firebasestorage.app',
    measurementId: 'G-3F0JTWZ4DF',
  );
}
